[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@localhost:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"
[chains.eth-ropsten]
shard = "primary"
protocol = "ethereum"
provider = [
  { label = "firehose", details = { type = "firehose", url = "https://ropsten.streamingfast.io", token = "$STREAMING_FAST_API_TOKEN" }},
  { label = "peering", url = "http://localhost:8545", features = [] },
]
# [chains.eth-battlefield]
# shard = "primary"
# protocol = "ethereum"
# provider = [
#   { label = "firehose", details = { type = "firehose", url = "http://localhost:13042" }},
#   { label = "peering", url = "http://localhost:8545", features = [] },
# ]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]